### PR TITLE
uniform log messages for benchmark proof generation/verification

### PR DESCRIPTION
**Pull request by AronisAt79**
### Description

  Log messages across different prover benchmark tests differ slightly. This PR makes them uniform to make it easier to
  parse and report results

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
## Files Modified: 
```
circuit-benchmarks/src/bytecode_circuit.rs
circuit-benchmarks/src/copy_circuit.rs
circuit-benchmarks/src/evm_circuit.rs
circuit-benchmarks/src/packed_multi_keccak.rs
circuit-benchmarks/src/pi_circuit.rs
circuit-benchmarks/src/super_circuit.rs
circuit-benchmarks/src/copy_circuit.rs
circuit-benchmarks/src/exp_circuit.rs
circuit-benchmarks/src/tx_circuit.rs
```

### CODE REVIEW

**Review by ChihChengLiang — COMMENTED** [review]
This fix looks fragile to me. The parsing relies on the correctness of the log messages.
But the circuit developers need to be made aware of this dependency and might change the log messages accidentally in the future.

What do you think we define constants of benchmark IDs? For example

```rust
// Benchmark server parses the benchmark result using this string.
const BENCHMARK_ID_BYTECODE_CIRCUIT = "BytecodeCircuit";
```
Then in the proof message, we have

```rust
let proof_message = format!("{} Proof generation with {} rows", BENCHMARK_ID_BYTECODE_CIRCUIT, degree);
```
So that future developers wouldn't change the message accidentally and cause the parsing to fail.

**Comment by AronisAt79** [comment]
> This fix looks fragile to me. The parsing relies on the correctness of the log messages. But the circuit developers need to be made aware of this dependency and might change the log messages accidentally in the future.
> 
> What do you think we define constants of benchmark IDs? For example
> 
> ```rust
> // Benchmark server parses the benchmark result using this string.
> const BENCHMARK_ID_BYTECODE_CIRCUIT = "BytecodeCircuit";
> ```
> 
> Then in the proof message, we have
> 
> ```rust
> let proof_message = format!("{} Proof generation with {} rows", BENCHMARK_ID_BYTECODE_CIRCUIT, degree);
> ```
> 
> So that future developers wouldn't change the message accidentally and cause the parsing to fail.

Thanks @ChihChengLiang. It makes sense. I will apply your proposal.

**Review by ChihChengLiang — APPROVED** [review]
LGTM. Thanks for applying the suggestions.

**Comment by AronisAt79** [comment]
> LGTM. Thanks for applying the suggestions.

Thanks @ChihChengLiang. I pushed a new commit  with fmt changes cause rustfmt ci check was failing. Unless @CPerezz or/and @ed255 would like to also review, i will merge in one hour.

**Review by ed255 — APPROVED** [review]
LGTM!

**Pull request merged**
