### PR TITLE
MPT: merge with main only

### PR DESCRIPTION
**Pull request by Brechtpd**
### Description

Just merges the MPT branch with the master, without fixing any issues (and so breaks the code). The actual merge is done in https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1531, the only purpose of this PR is to have a nicer diff for the other PR without breaking the code in the current `mpt2` branch.

### Issue Link

[_link issue here_]

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Contents

- [_item_]

### Rationale

[_design decisions and extended information_]

### CODE REVIEW

**Review by ChihChengLiang — APPROVED** [review]
LGTM, as this is a merging main PR.

**Review by miha-stopar — APPROVED** [review]

**Comment by ChihChengLiang** [comment]
Hi @Brechtpd, what's the status of this PR? Anything we can help?

**Comment by Brechtpd** [comment]
This PR could be merged into the `mpt2` branch, it's just that without merging in https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1531 into this PR first, that would break the `mpt2` branch.

So I was thinking merging https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1531 first so the branch `mpt-main-sync` in this PR gets updated and then merge this PR into `mpt-2` is a way to do the merging without breaking any branches, but if you prefer something else let me know.

**Comment by ChihChengLiang** [comment]
Ｗonderful. Merging https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1531 first sounds good.

**Pull request merged**
