### PR TITLE
bus-mapping: fix return data offset and length bookkeeping

### PR DESCRIPTION
**Pull request by pinkiebell**
This resolves a problem with the returndatacopy opcode because of zero return_data.[offset, length]

### CODE REVIEW

**Review by han0110 — APPROVED** [review]
Nice catch!

**Review by DreamWuGit — APPROVED** [review]

**Comment by CPerezz** [comment]
Getting errors in some `RETURN/REVERT` tests. We might need to take another look to it @pinkiebell 
 :cry:

**Comment by pinkiebell** [comment]
> Getting errors in some `RETURN/REVERT` tests. We might need to take another look to it @pinkiebell
> 😢

That's odd. Looks like `call.return_data_offset` is intended for something else 🤔

**Comment by pinkiebell** [comment]
Well that worked. It's still a little bit confusing 🤷

**Review by han0110 — APPROVED** [review]
> Well that worked. It's still a little bit confusing 🤷

Sorry, I was also confused, so `call.return_data_offset` and `call.return_data_length` is recording the value specified by caller (destination for return data to be copied to when call end). See:

https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/83bfbef71fc006fab4a07fc8a830745e916055bc/bus-mapping/src/circuit_input_builder/input_state_ref.rs#L633-L646

**Comment by pinkiebell** [comment]
> > Well that worked. It's still a little bit confusing 🤷
> 
> Sorry, I was also confused, so `call.return_data_offset` and `call.return_data_length` is recording the value specified by caller (destination for return data to be copied to when call end). See:
> 
> https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/83bfbef71fc006fab4a07fc8a830745e916055bc/bus-mapping/src/circuit_input_builder/input_state_ref.rs#L633-L646

That makes more sense now 😅

**Comment by pinkiebell** [comment]
@DreamWuGit Please review again :)

**Review by lispc — APPROVED** [review]

**Pull request merged**
