### PR TITLE
fix: add `mock` dependency to zkevm-circuit `dev-dependencies`

### PR DESCRIPTION
**Pull request by silathdiir**
It seems that test build is failed when running `cargo test` (without `--all-features` or `--feature test`) in `zkevm-circuit` folder.
```
error[E0433]: failed to resolve: use of undeclared crate or module `mock`
   --> zkevm-circuits/src/copy_circuit.rs:694:9
    |
694 |     use mock::test_ctx::helpers::account_0_code_account_1_no_code;
    |         ^^^^ use of undeclared crate or module `mock`
```
`mock` dependency was set to optional in PR https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/786.
Fixed to add `mock` to `dev-dependencies` in `Cargo.toml` for tests.

### CODE REVIEW

**Review by pinkiebell — APPROVED** [review]
LGTM. After looking at the deps, I saw that `ethers-signers` could also be made optional like the `mock` depdendency and added to `test = [...]`. Would be nice nice if you include that change too 👍

**Comment by silathdiir** [comment]
> LGTM. After looking at the deps, I saw that `ethers-signers` could also be made optional like the `mock` depdendency and added to `test = [...]`. Would be nice nice if you include that change too 👍

Fixed to update `ethers-signers` to optional (in `dependencies` section) and associate it with feature `test`.

**Review by pinkiebell — APPROVED** [review]
LGTM

**Comment by pinkiebell** [comment]
@silathdiir Feel free to merge 👌

**Pull request merged**
