### PR TITLE
(rebase) : Deduplication of gen_blockchain_data.rs

### PR DESCRIPTION
**Pull request by protocolwhisper**
### Description

Extract functions from code duplication to make it more readable.

### Issue Link

This solves https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1556

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Rebase code(non-breaking change)

### Contents

- gen_blockchain_data.rs

### How Has This Been Tested?

The module is already failing before making changes

<hr>
```
This PR contains:
- Creating of four functions that refactor the use of deploy, get_block_number, blocks.insert, deployments.insert.

### CODE REVIEW

**Comment by ChihChengLiang** [comment]
Hi @protocolwhisper,
Please fix the issues reported in the CI.
Try running `cargo build` and `make clippy` to reproduce the failing locally.

**Comment by protocolwhisper** [comment]
@ChihChengLiang I fixed the errors. Looking at it again, I noticed that extracting the 'deploy' function would mean adding a bunch of imports and modifying the `Cargo.toml`. To me, this seems messier than the current setup. Let me know what you think :)

**Comment by protocolwhisper** [comment]
Just formatted it and now it's passing. @ChihChengLiang

**Review by ChihChengLiang — CHANGES_REQUESTED** [review]
Hi @protocolwhisper,

Thanks for the contribution, and I'm sorry for the late review! I gave my first round of review and noticed some changes are required. Please check my comments.

**Comment by ChihChengLiang** [comment]
> I fixed the errors. Looking at it again, I noticed that extracting the 'deploy' function would mean adding a bunch of imports and modifying the Cargo.toml. To me, this seems messier than the current setup. Let me know what you think :)

Hi @protocolwhisper, can you elaborate on this? What kind of error messages did you see when extracting the deploy function and what kind of imports do we need to add?

**Comment by ed255** [comment]
Hi @protocolwhisper, do you plan to continue working on this?

**Comment by ed255** [comment]
Closing due to inactivity

**Pull request closed without merging**
