### PR TITLE
feat: add `shanghai` feature and make CI pass with Shanghai geth traces

### PR DESCRIPTION
**Pull request by silathdiir**
### Description

1. Add Shanghai related fields to chain config in geth-utils.

2. EIP-3651 (Warm COINBASE): add a new access-list write for coinbase to Begin TX.

3. Part of EIP-3860 (Limit and meter initcode): only add gas cost of init code to Begin TX (missing gas cost changes in Create and OOG Create).

### Issue Link

Issue https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1362

Local related PRs:
https://github.com/scroll-tech/zkevm-circuits/pull/497
https://github.com/scroll-tech/zkevm-circuits/pull/500
https://github.com/scroll-tech/zkevm-circuits/pull/507

Reference previous PR:
https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1361

### Type of change

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### How Has This Been Tested?

Unit test cases of CI could pass with Shanghai geth traces.

### CODE REVIEW

**Review by ed255 — COMMENTED** [review]
The implementation looks good to me but I would like to discuss the feature approach.
So far we haven't introduced any rust feature to support new hard forks, we just implement the latest EIPs included.  This PR introduces a feature so that the zkevm can be built with/without shanghai support.  In which cases do we want to built without shanghai?
The code would look simpler without the rust feature, having shanghai implemented unconditionally.  Could you give some thoughts on why implement this under a rust feature?

**Comment by silathdiir** [comment]
> The implementation looks good to me but I would like to discuss the feature approach. So far we haven't introduced any rust feature to support new hard forks, we just implement the latest EIPs included. This PR introduces a feature so that the zkevm can be built with/without shanghai support. In which cases do we want to built without shanghai? The code would look simpler without the rust feature, having shanghai implemented unconditionally. Could you give some thoughts on why implement this under a rust feature?

Yes. I see. I will delete related feature guard of `shanghai` (and update some code) in this PR. Thanks.

When started to implement shanghai EIPs, we also supposed to upgrade `testool`, and could not confirm the difference between shanghai and not-shanghai.

After finishing shanghai EIPs, we [upgraded testool](https://github.com/scroll-tech/zkevm-circuits/pull/511) and run for both shanghai and not-shanghai via this feature guard. And it seems to be not much different.

with-shanghai (`24` Panic):
https://circuit-release.s3.us-west-2.amazonaws.com/testool/default.1684984242.79c0291.html
without-shanghai (`25` Panic):
https://circuit-release.s3.us-west-2.amazonaws.com/testool/default.1684984542.79c0291.html

**Review by lispc — APPROVED** [review]

**Review by ed255 — APPROVED** [review]
LGTM! Thanks for working on this!

**Comment by ed255** [comment]
This is ready to be merged once the branch is rebased against main.

**Pull request merged**
