### PR TITLE
Unify table dev-assign and real-assign.

### LINKED ISSUE #984: refactor: unify table dev_load and real assignment
for tables like tx table and keccak table, when we change the table layout later, we need to change codes both in dev_load and real assignment. Maybe error prone

### LINKED ISSUE #1034: Bug: xxxCircuit.txs feild should be withness::Transaction  instead of eth_types::geth_types::Transaction
https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/69c0a4a2b10aade85e8f44f21e1bdb2be842b2e1/zkevm-circuits/src/pi_circuit.rs#L1122-L1127

https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/69c0a4a2b10aade85e8f44f21e1bdb2be842b2e1/zkevm-circuits/src/tx_circuit.rs#L324-L334

### PR DESCRIPTION
**Pull request by SuccinctPaul**
This pr is seperated as #984 and .... , finished tasks are details on Done List. 
The left tasks and problems **not in this pr** are details on LEFT-TASKS List.

> Because there are lots of conflicts. So the `Done list` will become `Todo List` for new prs.

#### ~~Done List ~~  TODO List :
1. Unify method's name for the related method.
   * `load`: load data to table. It invokes `assignments` and `assign_row`
   * `assignments` : generate the assigned data for table.
   * `assign_row`: assign for a row of table, it specifies the assign structure of table
   * `XxxTableRow`: Specify the type for outputs of `assignments` and param of `assign_row`
2. Unify assign in tx_table and block_table.
3. Taking place of  `pi_circuit::BlockValues` by `witness::BlockContext`.
4. Resolved bug #1034 
5. Separate the table.rs into mods for better maintenance. #1402 

#### LEFT-TASKS List:
1. Unify table_assign for KeccakTable, 
   * Refacting its circuit first for much looser coupling will help to make this done. 
2. Unify `assignments` method in  rw_table and mpt_table  
   * Refacting its witnesses(Rw, Mpt) first for much looser coupling will help to make this done. 
3.  Define the assign related methods(Done.1) in Trait 
    * After unify the KeccakTable / rw_table / mpt_table to do this will be better.

### CODE REVIEW

**Comment by ChengYueJia** [comment]
Hi @aguzmant103 , could you help to assign reviewers ?

**Comment by aguzmant103** [comment]
@ed255 assigned as a reviewer due to automatic zkevm-reviewers list but let me know if you'd want me to reassign it!

**Comment by aguzmant103** [comment]
@ChengYueJia sorry for the long time to review your latest changes.

Can you resolve the latest conflicts? Afterwards @leolara can review it so we can merge this

**Comment by ChengYueJia** [comment]
> @ChengYueJia sorry for the long time to review your latest changes.
> 
> Can you resolve the latest conflicts? Afterwards @leolara can review it so we can merge this

Hi, @aguzmant103 @leolara , for there are lots of conflicts,  so I'll redo the `Done List` in some Prs.

> #### Done List:
> 5. Separate the table.rs into mods for better maintenance.
First, there is a new pr to finish Done#5. #1402 .  Please have a view of it.

**Comment by leolara** [comment]
@ChengYueJia so then this PR is not longer used and should be closed and we continue in the others?

**Comment by ChengYueJia** [comment]
> @ChengYueJia so then this PR is not longer used and should be closed and we continue in the others?

yep, I'll continue those update in new prs.  Agree to close this.

**Pull request closed without merging**
