### PR TITLE
[Fix] Constrain `code_source` to be 0 for root and create case

### PR DESCRIPTION
**Pull request by icemelon**
It'd be a bug that the constraint doesn't match the description.

### CODE REVIEW

**Comment by DreamWuGit** [comment]
seems to me old design is  `code_source ` refer to `tx_id` when it is root call ,  changed anywhere ?

**Comment by han0110** [comment]
This was left as a todo which makes the proving fail, but we should just remove this constraint and mark it as a todo. We can start to implement it after we decide how to handle opcode lookup of creation transaction (see appliedzkp/zkevm-specs#73).

**Comment by ed255** [comment]
> seems to me old design is `code_source ` refer to `tx_id` when it is root call , changed anywhere ?

As far as I know it's still like this.

I think it's better to follow @han0110 comment: remove this constraint and leave a TODO there.  Furthermore, in the witness converter or the function that assigns the values for the step state, we can add a `log::warning` that prints a message when `is_root` and `is_create` are both true.  This way we can get a nice message when trying a circuit with a functionality that is not yet implemented.

**Comment by DreamWuGit** [comment]
> > seems to me old design is `code_source ` refer to `tx_id` when it is root call , changed anywhere ?
> 
> As far as I know it's still like this.
> 
> I think it's better to follow @han0110 comment: remove this constraint and leave a TODO there. Furthermore, in the witness converter or the function that assigns the values for the step state, we can add a `log::warning` that prints a message when `is_root` and `is_create` are both true. This way we can get a nice message when trying a circuit with a functionality that is not yet implemented.

Agree !

**Comment by icemelon** [comment]
@ed255 @DreamWuGit Sounds good. I will change it into a TODO here and link to @han0110's issue about this.

**Pull request closed without merging**
