### PR TITLE
upgrade ethers-* packages to 0.17.0

### LINKED ISSUE #757: Consider upgrading the ethers-* crates
Lately, I encountered many dependency errors because bus-mapping and friends are using rather old versions of ethers-* packages. Maybe it's time to upgrade them 🙂

### PR DESCRIPTION
**Pull request by pinkiebell**
fixes #757

### CODE REVIEW

**Review by CPerezz — APPROVED** [review]
LGTM!!!  Thanks for the update @pinkiebell :tada:

**Comment by pinkiebell** [comment]
the `Vec::with_capacity` was something ethers don't want. Last commit should fix this issue 🙏

**Comment by pinkiebell** [comment]
Still broken :/ Any clue why?

```
Diff < left / right > :
[414](https://github.com/privacy-scaling-explorations/zkevm-circuits/runs/8270189883?check_suite_focus=true#step:8:415)
<Err(
[415](https://github.com/privacy-scaling-explorations/zkevm-circuits/runs/8270189883?check_suite_focus=true#step:8:416)
<    [
[416](https://github.com/privacy-scaling-explorations/zkevm-circuits/runs/8270189883?check_suite_focus=true#step:8:417)
<        Permutation {
[417](https://github.com/privacy-scaling-explorations/zkevm-circuits/runs/8270189883?check_suite_focus=true#step:8:418)
<            column: Column {
[418](https://github.com/privacy-scaling-explorations/zkevm-circuits/runs/8270189883?check_suite_focus=true#step:8:419)
<                column_type: Advice,
[419](https://github.com/privacy-scaling-explorations/zkevm-circuits/runs/8270189883?check_suite_focus=true#step:8:420)
<                index: 3,
[420](https://github.com/privacy-scaling-explorations/zkevm-circuits/runs/8270189883?check_suite_focus=true#step:8:421)
<            },
[421](https://github.com/privacy-scaling-explorations/zkevm-circuits/runs/8270189883?check_suite_focus=true#step:8:422)
<            location: InRegion {
[422](https://github.com/privacy-scaling-explorations/zkevm-circuits/runs/8270189883?check_suite_focus=true#step:8:423)
<                region: Region {
[423](https://github.com/privacy-scaling-explorations/zkevm-circuits/runs/8270189883?check_suite_focus=true#step:8:424)
<                    index: 8,
[424](https://github.com/privacy-scaling-explorations/zkevm-circuits/runs/8270189883?check_suite_focus=true#step:8:425)
<                    name: "tx table",
[425](https://github.com/privacy-scaling-explorations/zkevm-circuits/runs/8270189883?check_suite_focus=true#step:8:426)
<                },
[426](https://github.com/privacy-scaling-explorations/zkevm-circuits/runs/8270189883?check_suite_focus=true#step:8:427)
<                offset: 4,
[427](https://github.com/privacy-scaling-explorations/zkevm-circuits/runs/8270189883?check_suite_focus=true#step:8:428)
<            },
[428](https://github.com/privacy-scaling-explorations/zkevm-circuits/runs/8270189883?check_suite_focus=true#step:8:429)
<        },
[429](https://github.com/privacy-scaling-explorations/zkevm-circuits/runs/8270189883?check_suite_focus=true#step:8:430)
<        Permutation {
[430](https://github.com/privacy-scaling-explorations/zkevm-circuits/runs/8270189883?check_suite_focus=true#step:8:431)
<            column: Column {
[431](https://github.com/privacy-scaling-explorations/zkevm-circuits/runs/8270189883?check_suite_focus=true#step:8:432)
<                column_type: Advice,
[432](https://github.com/privacy-scaling-explorations/zkevm-circuits/runs/8270189883?check_suite_focus=true#step:8:433)
<                index: 104,
[433](https://github.com/privacy-scaling-explorations/zkevm-circuits/runs/8270189883?check_suite_focus=true#step:8:434)
<            },
[434](https://github.com/privacy-scaling-explorations/zkevm-circuits/runs/8270189883?check_suite_focus=true#step:8:435)
<            location: InRegion {
[435](https://github.com/privacy-scaling-explorations/zkevm-circuits/runs/8270189883?check_suite_focus=true#step:8:436)
<                region: Region {
[436](https://github.com/privacy-scaling-explorations/zkevm-circuits/runs/8270189883?check_suite_focus=true#step:8:437)
<                    index: 7,
[437](https://github.com/privacy-scaling-explorations/zkevm-circuits/runs/8270189883?check_suite_focus=true#step:8:438)
<                    name: "signature address verify",
[438](https://github.com/privacy-scaling-explorations/zkevm-circuits/runs/8270189883?check_suite_focus=true#step:8:439)
<                },
[439](https://github.com/privacy-scaling-explorations/zkevm-circuits/runs/8270189883?check_suite_focus=true#step:8:440)
<                offset: 0,
[440](https://github.com/privacy-scaling-explorations/zkevm-circuits/runs/8270189883?check_suite_focus=true#step:8:441)
<            },
[441](https://github.com/privacy-scaling-explorations/zkevm-circuits/runs/8270189883?check_suite_focus=true#step:8:442)
<        },
[442](https://github.com/privacy-scaling-explorations/zkevm-circuits/runs/8270189883?check_suite_focus=true#step:8:443)
<    ],
[443](https://github.com/privacy-scaling-explorations/zkevm-circuits/runs/8270189883?check_suite_focus=true#step:8:444)
>Ok(
[444](https://github.com/privacy-scaling-explorations/zkevm-circuits/runs/8270189883?check_suite_focus=true#step:8:445)
>    (),
[445](https://github.com/privacy-scaling-explorations/zkevm-circuits/runs/8270189883?check_suite_focus=true#step:8:446)
 )
 ```

**Comment by pinkiebell** [comment]
One last try until supper ^^

**Comment by pinkiebell** [comment]
> It was really tricky last time to make everything work for the signature as more than 4 crates interact in the circuit related to it. My suggestion is to check that you're indeed getting the expected sighash.

Indeed. I was confused by the naming scheme for `rlp(), rlp_signed(), rlp_unsigned()` looking at the source, `rlp()` returns what we want

**Review by ed255 — APPROVED** [review]
LGTM! Thanks for the upgrade :)

**Pull request merged**
