### PR TITLE
geth-utils: remove 10mb trace limit

### PR DESCRIPTION
**Pull request by pinkiebell**
I hit this one while testing the circuits

### CODE REVIEW

**Comment by han0110** [comment]
@adria0 I saw this limitation is added in https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/748, is there anything broken when the trace is too large? Otherwise I think it should be fine to process large trace.

**Comment by ed255** [comment]
I think that after this was merged some months ago https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/614 we shouldn't encounter massive memory usage in the traces (as I believe this was coming from having a memory snapshot at each step of the trace).  We just need to make sure that we're always querying the trace with `EnableMemory: false`.  I think this may not be the case when using the internal tracer.  See: https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/2235254416aefd1bc9b5592e4e06cd58f8516e2a/external-tracer/src/lib.rs#L48

**Review by ed255 — APPROVED** [review]
LGTM!  I think that without memory snapshots this check is unnecessary.  (We may still need to update some places to avoid requesting the memory snapshots from the trace)

**Comment by pinkiebell** [comment]
> I think that after this was merged some months ago #614 we shouldn't encounter massive memory usage in the traces (as I believe this was coming from having a memory snapshot at each step of the trace). We just need to make sure that we're always querying the trace with `EnableMemory: false`. I think this may not be the case when using the internal tracer. See:
> 
> https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/2235254416aefd1bc9b5592e4e06cd58f8516e2a/external-tracer/src/lib.rs#L48
> 
> @pinkiebell could you try setting the default `enable_memory` to `false` and see if all unit tests still pass?

Looks good 👌

**Review by han0110 — APPROVED** [review]
LGTM!

**Pull request merged**
