### PR TITLE
fix extcodecopy: non-exsit-proof, challenge api, and other fixes

### PR DESCRIPTION
**Pull request by lispc**
1.  use non-exist-proof
2. use challenge api
3. fix stack push order
4. add EXTERNAL_ADDRESS to TestContext
5. fix reversible_write_counter

previously, due to the incorrect param stack pushing order, an OOG error is triggered and handled by DummyGadget, so all the above errors cannot be catched by tests.

### CODE REVIEW

**Review by ed255 — APPROVED** [review]
LGTM overall! Thanks for the quick fix!

There's one detail I'd like to discuss.  With this circuit implementation, when the account doesn't exist the code_hash will be `0`.  Then a bytecode_length is done with this code_hash, which gives code_size = 0.  This BytecodeTable lookup will suceed because we have the 0 row in the BytecodeTable.
- I quickly looked at the Bytecode Circuit and I didn't find the assignation of an explicit 0 row.  Maybe I'm missing something, because AFAIK this row is required the EVM circuit to work (otherwise the bytecode lookups can never be disabled).
- In https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1046 I followed a different approach: https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/a6267835e4c5dccb991d803e9a4b25fff58986a2/zkevm-circuits/src/evm_circuit/execution/extcodesize.rs#L57-L66 But maybe using the 0-row is smarter because we avoid requiring the IsZeroGadget.  So maybe we can update it later (also for consistency).

**Comment by lispc** [comment]
the first issue may be related to https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/866 ? even we don't insert a full-0 row, it is there...

**Comment by ed255** [comment]
> the first issue may be related to #866 ? even we don't insert a full-0 row, it is there...

Oh you're right...  We should address #866.  So the reason why 0-row lookups suceed to the Bytecode Table is because the bottom rows that haven't been assigned and appear before the blinding rows are set to 0.  But they could be set to anything by the prover, making any arbitrary bytecode lookup suceed (in the current implementation)

**Review by roynalnaruto — APPROVED** [review]
Looks good to me!

**Pull request merged**
