### PR TITLE
refactor(evm_circuit): minor fix in end_tx (#1725)

### PR DESCRIPTION
**Pull request by curryrasul**
### Description

This PR is aimed to do minor style refactor/fix of #1719

### Issue Link

#1725 

### Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

### Content

This PR addresses issue #1725 to do a minor style fix, that @lispc mentioned [here](https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1719#issuecomment-1880469834)

### CODE REVIEW

**Review by lispc — APPROVED** [review]

**Review by ChihChengLiang — APPROVED** [review]
LGTM

**Review by ChihChengLiang — COMMENTED** [review]
Oh, wait, there's a test failing. Looks like invalid tx related.

**Comment by curryrasul** [comment]
> Oh, wait, there's a test failing. Looks like invalid tx related.

@ChihChengLiang that's strange, do you think that's because something wrong in the code? It shouldn't be though

**Comment by hero78119** [comment]
> > Oh, wait, there's a test failing. Looks like invalid tx related.
> 
> @ChihChengLiang that's strange, do you think that's because something wrong in the code? It shouldn't be though

Hi @curryrasul I think invalid_tx related error is due to invalid_tx also need to be change

https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/141348b41a5cfe60d72ae104db371e628feb1c21/zkevm-circuits/src/evm_circuit/execution/invalid_tx.rs#L79

also need to change to `7.expr()`.

The reason is for invalid tx,  virtual step `invalid_tx` will replaced `end_tx`. So the rw counter part also need to be adjusted accordingly

**Comment by curryrasul** [comment]
Should I squash the commits? @ChihChengLiang

**Comment by ChihChengLiang** [comment]
@curryrasul When you click the green merge button, GitHub squashes your commits. Feel free to merge anytime you feel ready.

**Pull request merged**
