### PR TITLE
support legacy tx with v in [0, 1]

### PR DESCRIPTION
**Pull request by smtmfft**
It seems the mainnet still accepts the legacy tx whose v is 0 or 1. So, add support to avoid InvalidSignature error

### CODE REVIEW

**Comment by aguzmant103** [comment]
@Brechtpd are you ok to help us one reviewer from your side?

**Comment by smtmfft** [comment]
add some corresponding tests before the formal reivew.

**Comment by ed255** [comment]
@smtmfft this PR has been in draft for a while, do you plan to continue working on this?

**Comment by ed255** [comment]
Closing this due to inactivity (long time being in draft).  @smtmfft feel free to make a new PR with the same contents if you'd like to work on this again!

**Pull request closed without merging**
