### PR TITLE
Merge return & revert state in the ExecutionState

### PR DESCRIPTION
**Pull request by icemelon**

### CODE REVIEW

**Comment by icemelon** [comment]
cc @z2trillion

**Review by ChihChengLiang — APPROVED** [review]
LGTM. Great addition

**Review by han0110 — APPROVED** [review]
LGTM!

Also when the case `RETURN && is_create`, it should update current callee's `code_hash`, but I can't find it anywhere, is that a missing lookup?

**Comment by z2trillion** [comment]
> Also when the case `RETURN && is_create`, it should update current callee's `code_hash`, but I can't find it anywhere, is that a missing lookup?

Yes, it's missing at the moment. I am working on updating the specs and the circuit to include this.

**Pull request merged**
