### PR TITLE
[word lo/hi] add ci subcircuit unit test and fix address assignment 

### PR DESCRIPTION
**Pull request by hero78119**
### Description

Add back 
- evm_circuit 
- keccak_circuit 
- exp_circuit 
- pi_circuit 
- state_circuit

unittest to ci

Other subcircuit `tx_circuit/copy_circuit/bytecode_circuit/root_circuit` still failed for now, will be fixed in another pr

### Issue Link

[N/A](https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1487)

### Type of change

- [x] New feature (non-breaking change which adds functionality)

### Contents

- Fix unittest assertion [failed](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/word-lo-hi/zkevm-circuits/src/util/int_decomposition.rs#L39-L43) due to sanity check on address H160 retrieved from U256. We need to clean up MSB 12 bytes to 0 
- add subcircuit light tests on CI in whitelist based

### CODE REVIEW

**Review by KimiWu123 — APPROVED** [review]
LGTM

**Comment by hero78119** [comment]
resolved https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1477 and https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1476

**Comment by KimiWu123** [comment]
tx_circuit passed in #1418

**Comment by hero78119** [comment]
> tx_circuit passed in #1418

👍 it's good. @KimiWu123 do you think I merge this first, since it just small pr, I think 1 reviewer is ok. So other word-lo-hi pr e.g. #1418 can add tx_circuit back on the same ci file

**Review by ed255 — APPROVED** [review]
LGTM!

**Pull request merged**
