### PR TITLE
[WIP] State circuit - config from file

### PR DESCRIPTION
**Pull request by miha-stopar**
Aims to enable state circuit having memory and stack ops and implement memory/stack switching constraints.

### CODE REVIEW

**Comment by therealyingtong** [comment]
[Force-pushed](https://github.com/appliedzkp/zkevm-circuits/compare/e5ad491eeb3cb16fc7c04359f233847847f96765..58c758b9bf04e0589c27162b785d2a7dab8f98a8) to rebase on #23.

**Comment by therealyingtong** [comment]
This currently conflicts with #23. Actually, it might be simpler to just merge this into #23.

**Comment by CPerezz** [comment]
Do we still plan to merge this @miha-stopar or can we close it?

**Comment by miha-stopar** [comment]
> Do we still plan to merge this @miha-stopar or can we close it?



> Do we still plan to merge this @miha-stopar or can we close it?

It's very old and doesn't make any sense any more, I think. Will close it.

**Pull request closed without merging**
