### PR TITLE
pad evm circuit to make vk/pk universal

### PR DESCRIPTION
**Pull request by lispc**
solves https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/474

### CODE REVIEW

**Comment by han0110** [comment]
Ah actually I mean to keep original selectors, but increase the degree of `execution_state_selector`  to halve the cells for `ExecutionState` (with a bit selector multiplied), to make `EndBlock` single row. Then we can pad the step with `EndBlock` all the way down.

https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/89ad0890149327b30ff8ffd5e3a32ac2cdb1c031/zkevm-circuits/src/evm_circuit/step.rs#L395-L404

My concern to turn `q_step_last` to advice column is it might introduce some constraint to make sure it's turned on at some row (and check some terminating conditions), but it seems this PR doesn't constrain this?

**Comment by lispc** [comment]
i see..the idea is similar to tag_bits in state circuit.    I don't have that implementation ready and maybe it would be left to others for implementation

**Comment by han0110** [comment]
Yes exactly. Sorry for confusing, let's see if anyone is interesting in this issue.

**Comment by CPerezz** [comment]
Superset by #728

**Pull request closed without merging**
