### PR TITLE
circuit for maxcodesize exceed & code store oog

### PR DESCRIPTION
**Pull request by DreamWuGit**
### Description

circuit for maxcodesize exceed & code store oog
markdown spec is https://github.com/privacy-scaling-explorations/zkevm-specs/pull/393
### Issue Link
#1259 

### Type of change

- [x] New feature (non-breaking change which adds functionality)

This PR contains:
- merge oog codestore and maxcodesize exceed error into one
- buss mapping & circuit
- tests for both two error cases(create / create2)
- fix get_step_err #1275 
- test for tx deploy (tx.to = null )

### Design choices

- make error check on `RETURN` op code not create itself.

### CODE REVIEW

**Comment by lispc** [comment]
there are 3 ways to deploy contracts CREATE opcode / CREATE2 opcode / tx.to = None .

seems only the first 2 are tested here?

**Comment by DreamWuGit** [comment]
> there are 3 ways to deploy contracts CREATE opcode / CREATE2 opcode / tx.to = None .
> 
> seems only the first 2 are tested here?

make sense , even `tx.to = None` use same `create` method in core/vm/evm.go, better to have single test for it.

**Comment by CPerezz** [comment]
We will need to add the `not STATICCALL` constraint in here as pointed in the specs PR.

I'll wait until we merge the specs to do the complete review. As this still needs to be updated.

**Comment by DreamWuGit** [comment]
> @DreamWuGit just following up, have you had a chance to update this PR?

will update & rebase soon!

**Comment by DreamWuGit** [comment]
@aguzmant103  I notice this is create gadget related error, now create gadget PR still pending not merged , so a few test failed.

**Comment by ed255** [comment]
Current status of this PR is that it depends on create gadget:
- https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1356
- https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1357
- https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1358

**Comment by KimiWu123** [comment]
@silathdiir , is this PR ready for review?

**Comment by silathdiir** [comment]
> @silathdiir , is this PR ready for review?

Sorry, no. I haven't started to work on it. Will start to fix it in next week.

**Comment by DreamWuGit** [comment]
this PR is much outdated, make new one here https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1545, closing this one now.

**Pull request closed without merging**
