### PR TITLE
Fix CI Checks workflow to support ephemeral GH runners

### PR DESCRIPTION
**Pull request by ntampakas**

### CODE REVIEW

**Review by pinkiebell — APPROVED** [review]
LGTM. What about the other workflows, gradually replacing them?

**Comment by ntampakas** [comment]
> LGTM. What about the other workflows, gradually replacing them?

Exactly, that' s the plan!

**Comment by pinkiebell** [comment]
@ChihChengLiang I think we need to 'force' merge here. Looks like `Test (ci-checks-runner)` is a stale check that can never be executed because it was changed via this PR.

**Comment by ChihChengLiang** [comment]
Hi @pinkiebell @ntampakas, I've removed the branch protection rule that requires Test (ci-checks-runner)

**Review by ChihChengLiang — APPROVED** [review]
LGTM.

**Pull request merged**
