### PR TITLE
Create generator-generic-ossf-slsa3-publish.yml

### PR DESCRIPTION
**Pull request by Mariuszok12**
### Description

[_PR description_]

### Issue Link

[_link issue here_]

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [ ] Refactor (no updates to logic)

### Contents

- [_item_]

### Rationale

[_design decisions and extended information_]

### How Has This Been Tested?

[_explanation_]

<hr>

## How to fill a PR description 

Please give a concise description of your PR.

The target readers could be future developers, reviewers, and auditors. By reading your description, they should easily understand the changes proposed in this pull request.

MUST: Reference the issue to resolve

### Single responsibility

Is RECOMMENDED to create single responsibility commits, but not mandatory.

Anyway, you MUST enumerate the changes in a unitary way, e.g.

```
This PR contains:
- Cleanup of xxxx, yyyy
- Changed xxxx to yyyy in order to bla bla
- Added xxxx function to ...
- Refactored ....
```

### Design choices

RECOMMENDED to:
- What types of design choices did you face?
- What decisions you have made?
- Any valuable information that could help reviewers to think critically

### CODE REVIEW

**Review by Mariuszok12 — COMMENTED** [review]
Zatwierdź

**Comment by Mariuszok12** [comment]
[Pull Request Labeler](https://github.com/privacy-scaling-explorations/zkevm-circuits/actions/workflows/labeler.yml)

**Comment by Mariuszok12** [comment]
https://github.com/privacy-scaling-explorations/zkevm-circuits/actions/workflows/labeler.yml/badge.svg?branch=main&event=create

**Comment by ed255** [comment]
Closed due to missing PR description and context.

**Pull request closed without merging**
