### PR TITLE
Compile time of configure gadget

### PR DESCRIPTION
**Pull request by naure**
### Description

This improves compilation times. 

### Issue Link

No issue, quality-of-life PR.

### Type of change

- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Contents

The function `configure_gadget` is split into a generic and a non-generic functions.

### Rationale

Generics are not free. They are the biggest contributor to compile times and to CPU code cache. `configure_gadget` is the largest example of this phenomenon.

I measured about 2x fewer LLVM IR with `cargo llvm-lines`. Even 3x in Scroll’s fork. The improvement in clock time depends a lot on exactly what you do, but it will be faster.

### How Has This Been Tested?

    cargo test --features test -p zkevm-circuits --release

### CODE REVIEW

**Comment by hero78119** [comment]
Hi @naure The changes looks neat to me!!
Just wanna further ask, is there more insightful elaboration/reference on why this craft trick can improve compiling time instead of compiler optimize itself?  
Want to learn more and see whether can also optimise other parts in current codebase

**Comment by naure** [comment]
The [Rust Performance Book](https://nnethercote.github.io/perf-book/compile-times.html#llvm-ir)!

**Comment by naure** [comment]
The next largest occurence of this would be `create_gate`. That one should be fixed naturally along with this improvement: https://github.com/privacy-scaling-explorations/halo2/issues/144

**Review by ed255 — APPROVED** [review]
LGTM! This is really nice!

The github action for this PR took `6m 28s` to build the tests  (see https://github.com/privacy-scaling-explorations/zkevm-circuits/actions/runs/4266506184/jobs/7427108345)
Previoulsy this was `7m 13s` (see https://github.com/privacy-scaling-explorations/zkevm-circuits/actions/runs/4303670677/jobs/7503692807)

So it's a reduction of more than 1 minute :D

**Pull request merged**
