### PR TITLE
fix github CI

### PR DESCRIPTION
**Pull request by 0xmountaintop**

### CODE REVIEW

**Review by CPerezz — APPROVED** [review]
LGTM.

Would like the approval from @AronisAt79 or @ntampakas .

It's a bit strange as the CI works fine now. And seeing this, it shouldn't..

**Comment by ntampakas** [comment]
utACK!

**Review by ntampakas — COMMENTED** [review]
Minor comment:
We could change also in the future, cache version from v2 -> v3

**Review by ntampakas — APPROVED** [review]
utACK

**Comment by CPerezz** [comment]
> Minor comment:
> We could change also in the future, cache version from v2 -> v3

Could you file an issue for it????

**Pull request merged**
