### PR TITLE
optim/opcode-stats: print more detailed metrics per opcode

### PR DESCRIPTION
**Pull request by naure**
Run with

    cargo test -p zkevm-circuits --features mock --release get_evm_states_stats -- --nocapture --ignored

[Current Metrics](https://github.com/privacy-scaling-explorations/zkevm-circuits/files/9891417/opcode_metrics2.txt)

### CODE REVIEW

**Review by CPerezz — COMMENTED** [review]
@naure Sorry because this has fallen behind and It's something we're definitely interested on having!!

2 major comments: 
1- You mention this is behind the `mock` feature but in `Cargo.toml` there's no `mock` feature defined and neither is the instrumentiation conditionally compiled with that. 
I'd suggest to add this as we might not want the overhead of the instrumenter a lot of times.

2- I'd suggest that to have a better formatting of the tables, we use something like: https://crates.io/crates/cli-table. This should make a lot easier to have a structured printing.

Please tell us if you're interested on keeping up with this work. Otherwise we'll pick it up!

**Comment by aguzmant103** [comment]
Hey @naure just following up with you. Are you able to continue with this work? Thanks for the help!

**Comment by CPerezz** [comment]
> Hey @naure just following up with you. Are you able to continue with this work? Thanks for the work so far!

If @naure doesn't show up I'll pick up this and update it in order to merge it.

**Comment by aguzmant103** [comment]
@CPerezz  assigning this to you

**Comment by aguzmant103** [comment]
We're going to close this as this is not required in the near future and it became stale. In the mid future if we need it again we can use this as reference.

**Comment by ed255** [comment]
ping @CPerezz we discussed this in an offline conversation

**Pull request closed without merging**
