### PR TITLE
Add the Super Circuit to the set of integration tests

### PR DESCRIPTION
**Pull request by xiaodino**
https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/749

### CODE REVIEW

**Review by han0110 — APPROVED** [review]
LGTM!

**Comment by xiaodino** [comment]
> 

Resolved merge conflicts.

**Comment by xiaodino** [comment]
> @xiaodino LGTM, anyway seems that there's some conflicts that needs to be addessed.

taikochain:xiaodino/integration-tests-super-circuit

**Comment by xiaodino** [comment]
> @xiaodino LGTM, anyway seems that there's some conflicts that needs to be addessed.

Resolved merge conflicts

**Pull request merged**
