### PR TITLE
pse-keccak-test-vector: test concrete hash results from KeccakCircuit

### PR DESCRIPTION
**Pull request by naure**
### Description

This adds a unit test that verifies the concrete content of the Keccak lookup table. This clarifies what the circuit does.

Depends on a MockProver addition: https://github.com/privacy-scaling-explorations/halo2/pull/153

### Issue Link

This will serve as a regression test before other changes (e.g., #1016, #1203, #1241, etc).

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Contents

- Add expected Keccak digests.
- Compute RLC values. The challenges come from the challenge API implemented by the MockProver.
- Check that all requested hashes are there.
- Check that empty entries for padding are valid.

### CODE REVIEW

**Comment by naure** [comment]
This PR cannot pass the tests yet because this repo is not yet in-sync with the branch `main` of `halo2`.

**Comment by ChihChengLiang** [comment]
blocked by #1366

**Comment by ed255** [comment]
@naure the halo2 dependency has been updated for some time.  Would you like to continue working on this?

**Comment by ed255** [comment]
Closing due to inactivity.  @ChihChengLiang plans to take this over via a new PR

**Pull request closed without merging**
