### PR TITLE
Feat/#1518 ErrorOutOfGasStaticMemoryExpansion error state

### LINKED ISSUE #1518: Complete the test of `ErrorOutOfGasStaticMemoryExpansion` error state
### Describe the feature you would like

`ErrorOutOfGasStaticMemoryExpansion` handler was implemented but without any testing.

### Additional context

Scroll's PR: https://github.com/scroll-tech/zkevm-circuits/pull/327

### PR DESCRIPTION
**Pull request by KimiWu123**
### Description

This PR was pulled from Scroll team (https://github.com/scroll-tech/zkevm-circuits/pull/327) and 1. supported uint64 overflow and fitted to our word lo/hi design.

### Issue Link

closed #1518

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by KimiWu123** [comment]
@DreamWuGit , could you help review this PR?

**Comment by lispc** [comment]
hi @KimiWu123 ,  i don't know by "pulled from Scroll team" you only checked that PR, or includes later changes of these files too?   That pr is half year ago, and we usually do testing & fixing, so it is possible that we added more improvements later.  So my suggestion would be, it is usually better to check latest scroll-tech/zkevm-circuits develop branch than only check one single old PR.

**Comment by KimiWu123** [comment]
> hi @KimiWu123 , i don't know by "pulled from Scroll team" you only checked that PR, or includes later changes of these files too? That pr is half year ago, and we usually do testing & fixing, so it is possible that we added more improvements later. So my suggestion would be, it is usually better to check latest scroll-tech/zkevm-circuits develop branch than only check one single old PR.

What I did is pulled your PR and compared with our spec. Thanks for your advise,and I'll check your dev brach as well.

**Comment by DreamWuGit** [comment]
PR #1558 merged, this PR can use new `MemoryExpandedAddressGadget` now.

**Review by davidnevadoc — APPROVED** [review]
LGTM :+1:

**Pull request merged**
