### PR TITLE
Add test for the codehash of the coinbase account.

### PR DESCRIPTION
**Pull request by z2trillion**
### Description
Previously we did not set the code hash for coinbase accounts in the EndTxGadget. This was fixed in 242d38b44730d9766661c885d0a27df00589ce39. This PR adds a regression test.

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by ChihChengLiang** [comment]
Hi @z2trillion, what's the status on this PR?

**Comment by z2trillion** [comment]
Sorry, I forgot about this.

The originally failing test now doesn't fail because of 242d38b44730d9766661c885d0a27df00589ce39, so now this PR consists of the regression test only. Feel free to close if it that's no longer needed.

**Review by ChihChengLiang — APPROVED** [review]
LGTM. Thanks for adding the regression test.

**Review by han0110 — APPROVED** [review]
LGTM

**Pull request merged**
