### PR TITLE
Keccak integration tests and more

### PR DESCRIPTION
**Pull request by leolara**
### Description

Add keccak to integration tests, and solve some issues that also fix variadic problem for Super Circuit integration test.

### Issue Link

Closes https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1128
Closes https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1208
Closes https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1209
Closes https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1212

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Contents

- Keccak integration tests should not have keccak_padding: None. 
- SuperCircuit integration tests: make it non variadic.
- Add keccak circuit to integration tests. 
- Unify circuits params dynamic / static encodings. 

### Rationale

In the issues.

### How Has This Been Tested?

Integration test mock prover passes. The integration test actual prover does not pass because of unrelated bug https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1016

### CODE REVIEW

**Comment by leolara** [comment]
Although the mock test passes and the fixed columns are the same, the actual prover gives an "ConstraintSystemFailure" error for all blocks with the keccak integration test.

Perhaps it is better to integrate the permutations check to the mock prover to see if that is the reason?

**Comment by lispc** [comment]
oh i think i know the reason... i remember in the upstream keccak circuit, phase 2 cells and phase 1 cells are mixed in same columns.. so the commitment of phase1 columns(used to derive challenges), are not the real commitment that should be used in vanishing poly... so https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1016 is not only a "soundness" issue..      

we have a solution https://github.com/scroll-tech/zkevm-circuits/pull/308 if you think it is ok, we can PR here.

**Comment by ed255** [comment]
> Although the mock test passes and the fixed columns are the same, the actual prover gives an "ConstraintSystemFailure" error for all blocks with the keccak integration test.

> Perhaps it is better to integrate the permutations check to the mock prover to see if that is the reason?

I think that's the best next step!

**Comment by ed255** [comment]
> oh i think i know the reason... i remember in the upstream keccak circuit, phase 2 cells and phase 1 cells are mixed in same columns.. so the commitment of phase1 columns(used to derive challenges), are not the real commitment that should be used in vanishing poly... so #1016 is not only a "soundness" issue..
> 
> we have a solution [scroll-tech#308](https://github.com/scroll-tech/zkevm-circuits/pull/308) if you think it is ok, we can PR here.
> 
> super circuit in scroll fork works well, no problem when real proving

Thanks for sharing this information!

I have just tested the real prover for the keccak integration tests using the branch in this PR, but generating the setup with the block used in the proof and it still fails; so everything checks out and the issue must not be in the permutations but in the Challange API as you pointed out!

I checked that PR and looks good to me to be merged into our repo :)

**Review by CPerezz — APPROVED** [review]
LGTM!

**Pull request merged**
