### PR TITLE
[WIP] MPT inserted ext node

### PR DESCRIPTION
**Pull request by miha-stopar**
This PR covers the case when extension node is inserted at the place of the existing extension node. The old extension node gets modified - it now has a different number of nibbles.

Some more info here: https://github.com/privacy-scaling-explorations/zkevm-specs/issues/268

### CODE REVIEW

**Comment by ChihChengLiang** [comment]
@miha-stopar is this PR still being worked on? Can we close it if it isn't?

**Comment by miha-stopar** [comment]
> @miha-stopar is this PR still being worked on? Can we close it if it isn't?

@ChihChengLiang I am porting it to the refactored MPT code, so I am still looking at it. Can it remain open for a bit more?

**Comment by ChihChengLiang** [comment]
Sounds good. Let's keep it open.

**Comment by ed255** [comment]
We're keeping this PR for reference but the plan is to port the code to the current MPT implementation.  After this is done we'll close this PR.

**Comment by miha-stopar** [comment]
Closed in favour of https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1685.

**Pull request closed without merging**
