### PR TITLE
[keccak] use tag to stack lookup table cells

### PR DESCRIPTION
**Pull request by ChihChengLiang**
These tables are using few rows:

- range 12
- range 169
- special chunks (13+1) *13/2 =91 rows

We can use tags to let them share table columns.

It can be unblocked by adding some generic gates.

### CODE REVIEW

**Comment by CPerezz** [comment]
Added this PR to https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/489 as it closes one of the last 2 actions to take.

Would you like to do the latest one about the Iotas @ChihChengLiang ??

**Comment by CPerezz** [comment]
Looking nice so far! 

Will this also refactor how we create the tables for the `Iota` and `Mixing` and `KeccakF` tests @ChihChengLiang ?

**Comment by ChihChengLiang** [comment]
> Will this also refactor how we create the tables for the Iota and Mixing and KeccakF tests

@CPerezz For KeccakF yes. Mixing will be refactored out. Iota doesn't need tables.

**Review by CPerezz — APPROVED** [review]
LGTM.

Amazing work on simplifying the circuits that depend on these lookups!

**Pull request merged**
