### PR TITLE
Remove build.rs in circuit-benchmarks

### PR DESCRIPTION
**Pull request by ChihChengLiang**
### Description

We remove the build.rs and assign DEGREE in a sane way.

### Issue Link

#1217

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Design choices

I face a design choice to assign the default value for the DEGREE. The original build.rs assigns them as 19. But in the fix, I can assign different default values for exp, pi, and tx circuits. I still assign them 19 to maintain the same behavior.

Note for reviewers. I'm not sure if this breaks the benchmark flow or introduces dead code to the benchmark script. The `execBench.sh` runs this line `DEGREE=$k ~/.cargo/bin/cargo test --profile bench bench_${run_suffix} -p circuit-benchmarks --features benches  -- --nocapture > "$target_dir/$logfile" 2>&1`. I believe the `DEGREE=$k` was used in both the build time for build.rs before and the run time now. So I expect the bench to work in this fix too.

### CODE REVIEW

**Comment by ChihChengLiang** [comment]
Thank you @AronisAt79 for discovering this issue. 😃

**Comment by CPerezz** [comment]
Did benchmarks run @AronisAt79 ?? I can't spot it

**Review by CPerezz — APPROVED** [review]
LGTM once we see no benches are broken due to this change!

**Comment by CPerezz** [comment]
@AronisAt79 the benchmarks seem broken: 
```
Run ssh prover "bash -s" -- < .github/proverCiScripts/execBench.sh "1218" 19 '"benchmarks: ALL"'
  ssh prover "bash -s" -- < .github/proverCiScripts/execBench.sh "1218" 19 '"benchmarks: ALL"'
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    PR_NUMBER: 1218
To be implemented
Error: Process completed with exit code 1.
```

**Comment by AronisAt79** [comment]
> @AronisAt79 the benchmarks seem broken:
> 
> ```
> Run ssh prover "bash -s" -- < .github/proverCiScripts/execBench.sh "1218" 19 '"benchmarks: ALL"'
>   ssh prover "bash -s" -- < .github/proverCiScripts/execBench.sh "1218" 19 '"benchmarks: ALL"'
>   shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
>   env:
>     PR_NUMBER: 1218
> To be implemented
> Error: Process completed with exit code 1.
> ```
The "ALL" choice is not implemented in workflow level, as we had said in the past that we dont want to stall a PR waiting for all benches to finish. Do we need this after all?
The EVM one is working :).

**Review by AronisAt79 — APPROVED** [review]
LGTM as well!

**Pull request merged**
