### PR TITLE
Rename "state write" to "reversible write"

### PR DESCRIPTION
**Pull request by z2trillion**

### CODE REVIEW

**Review by ed255 — APPROVED** [review]
LGTM!

@z2trillion Would you like to update https://github.com/appliedzkp/zkevm-specs and https://github.com/appliedzkp/zkevm-docs/ as well? (they contain several references to `state_write_counter`)

**Review by han0110 — APPROVED** [review]
LGTM!

**Comment by z2trillion** [comment]
> LGTM!
> 
> @z2trillion Would you like to update https://github.com/appliedzkp/zkevm-specs and https://github.com/appliedzkp/zkevm-docs/ as well? (they contain several references to `state_write_counter`)

Will do

**Review by miha-stopar — APPROVED** [review]
LGTM!

**Pull request merged**
